local icon = require('plugins.config.shared.icon')

require('dropbar').setup {
  icons = {
    enable = true,
    kinds = {
      use_devicons = true,
      symbols = {
        Array = icon.array .. ' ',
        Boolean = icon.boolean .. ' ',
        BreakStatement = icon.break_statement .. ' ',
        Call = icon.call .. ' ',
        CaseStatement = icon.case_statement .. ' ',
        Class = icon.class .. ' ',
        Color = icon.color .. ' ',
        Constant = icon.constant .. ' ',
        Constructor = icon.constructor .. ' ',
        ContinueStatement = icon.continue_statement .. ' ',
        Copilot = icon.copilot .. ' ',
        Declaration = icon.declaration .. ' ',
        Delete = icon.delete .. ' ',
        DoStatement = icon.do_statement .. ' ',
        Enum = icon.enum .. ' ',
        EnumMember = icon.enum_member .. ' ',
        Event = icon.event .. ' ',
        Field = icon.field .. ' ',
        File = icon.file .. ' ',
        Folder = icon.folder .. ' ',
        ForStatement = icon.for_statement .. ' ',
        Function = icon.func .. ' ',
        Identifier = icon.identifier .. ' ',
        IfStatement = icon.if_statement .. ' ',
        Interface = icon.interface .. ' ',
        Keyword = icon.keyword .. ' ',
        List = icon.list .. ' ',
        Log = icon.log .. ' ',
        Lsp = icon.lsp .. ' ',
        Macro = icon.macro .. ' ',
        MarkdownH1 = icon.markdown_h1 .. ' ',
        MarkdownH2 = icon.markdown_h2 .. ' ',
        MarkdownH3 = icon.markdown_h3 .. ' ',
        MarkdownH4 = icon.markdown_h4 .. ' ',
        MarkdownH5 = icon.markdown_h5 .. ' ',
        MarkdownH6 = icon.markdown_h6 .. ' ',
        Method = icon.method .. ' ',
        Module = icon.module .. ' ',
        Namespace = icon.namespace .. ' ',
        Null = icon.null .. ' ',
        Number = icon.number .. ' ',
        Object = icon.object .. ' ',
        Operator = icon.operator .. ' ',
        Package = icon.package .. ' ',
        Property = icon.property .. ' ',
        Reference = icon.reference .. ' ',
        Regex = icon.regex .. ' ',
        Repeat = icon.rep .. ' ',
        Scope = icon.scope .. ' ',
        Snippet = icon.snippet .. ' ',
        Specifier = icon.specifier .. ' ',
        Statement = icon.statement .. ' ',
        String = icon.string .. ' ',
        Struct = icon.struct .. ' ',
        SwitchStatement = icon.switch_statement .. ' ',
        Text = icon.text .. ' ',
        Type = icon.type .. ' ',
        TypeParameter = icon.type_parameter .. ' ',
        Unit = icon.unit .. ' ',
        Value = icon.value .. ' ',
        Variable = icon.variable .. ' ',
        WhileStatement = icon.while_statement .. ' ',
      },
    },
  },
  menu = {
    win_configs = {
      border = 'rounded',
    },
  },
}

vim.keymap.set('n', '<Leader>p', require('dropbar.api').pick)
