local icons = require('plugins.config.shared.icons')
require('symbols-outline').setup {
  symbols = {
    File = { icon = icons.file, hl = '@text.uri' },
    Module = { icon = icons.module, hl = '@namespace' },
    Namespace = { icon = icons.namespace, hl = '@namespace' },
    Package = { icon = icons.package, hl = '@namespace' },
    Class = { icon = icons.class, hl = '@type' },
    Method = { icon = icons.method, hl = '@method' },
    Property = { icon = icons.property, hl = '@method' },
    Field = { icon = icons.field, hl = '@field' },
    Constructor = { icon = icons.constructor, hl = '@constructor' },
    Enum = { icon = icons.enum, hl = '@type' },
    Interface = { icon = icons.interface, hl = '@type' },
    Function = { icon = icons.func, hl = '@function' },
    Variable = { icon = icons.variable, hl = '@constant' },
    Constant = { icon = icons.constant, hl = '@constant' },
    String = { icon = icons.string, hl = '@string' },
    Number = { icon = icons.number, hl = '@number' },
    Boolean = { icon = icons.boolean, hl = '@boolean' },
    Array = { icon = icons.array, hl = '@constant' },
    Object = { icon = icons.object, hl = '@type' },
    Key = { icon = icons.keyword, hl = '@type' },
    Null = { icon = icons.null, hl = '@type' },
    EnumMember = { icon = icons.enum_member, hl = '@field' },
    Struct = { icon = icons.struct, hl = '@type' },
    Event = { icon = icons.event, hl = '@type' },
    Operator = { icon = icons.operator, hl = '@operator' },
    TypeParameter = { icon = icons.type_parameter, hl = '@parameter' },
    Component = { icon = icons.component, hl = '@function' },
    Fragment = { icon = icons.fragment, hl = '@constant' },
  },
}

vim.keymap.set('n', '<Leader>s', '<Cmd>SymbolsOutline<CR>')
