require('which-key').setup {
  win = {
    border = 'rounded',
  },
  icons = {
    breadcrumb = '»',
    separator = '➜',
    group = '+',
    ellipsis = '…',
    keys = {
      Up = ' ',
      Down = ' ',
      Left = ' ',
      Right = ' ',
      C = '󰘴 ',
      M = '󰘵 ',
      S = '󰘶 ',
      CR = '󰌑 ',
      Esc = '󱊷 ',
      ScrollWheelDown = '󱕐 ',
      ScrollWheelUp = '󱕑 ',
      NL = '󰌑 ',
      BS = '⌫',
      Space = '󱁐 ',
      Tab = '󰌒 ',
      F1 = '󱊫',
      F2 = '󱊬',
      F3 = '󱊭',
      F4 = '󱊮',
      F5 = '󱊯',
      F6 = '󱊰',
      F7 = '󱊱',
      F8 = '󱊲',
      F9 = '󱊳',
      F10 = '󱊴',
      F11 = '󱊵',
      F12 = '󱊶',
    },
  },
}
